package com.revature.dtos;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.revature.postSets.Tag;
import lombok.Data;

import java.util.List;



@Data
@DynamoDBTable(tableName = "Sets")
public class SetDto {

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private List<String> tags;

    @DynamoDBAttribute
    private String author;

    @DynamoDBAttribute
    private boolean is_public;

}