package com.revature.post_sets;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "Sets")
public class Set {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private List<Tag> tags;

    @DynamoDBAttribute
    private List<Card> cards;

    @DynamoDBAttribute
    private String author;

    @DynamoDBAttribute
    private boolean is_public;

    @DynamoDBAttribute
    private int views;

    @DynamoDBAttribute
    private int plays;

    @DynamoDBAttribute
    private int studies;

    @DynamoDBAttribute
    private int favorites;


}
