package com.revature.post_sets;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;


@Data
@DynamoDBTable(tableName = "Tags")
public class Tag {

    @DynamoDBAttribute
    @DynamoDBHashKey
    private String name;

    @DynamoDBAttribute
    private String color;


    public Tag() {
        super();
    }

    public Tag(String name){
        this.name = name;
    }

}
