package com.revature.post_sets;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.revature.dtos.SetDto;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "Users")
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBHashKey
    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String profile_picture;

    @DynamoDBAttribute
    private int points;

    @DynamoDBAttribute
    private int wins;

    @DynamoDBAttribute
    private int losses;

    @DynamoDBAttribute
    private String registration_date;

    @DynamoDBAttribute
    private List<String> gameRecords;

    @DynamoDBAttribute
    private List<SetDto> created_sets;

    @DynamoDBAttribute
    private List<SetDto> favorite_sets;
}
